FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD EmbelSoftTest.jar /opt/EmbelSoftTest/
EXPOSE 8080
WORKDIR /opt/EmbelSoftTest/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "EmbelSoftTest.jar"]
